// Renders one of each email type to /tmp/email-previews/*.html so you
// can open them in a browser and visually check the new HTML styling.
//
// Usage:
//   npx tsx scripts/preview-emails.ts
//   open /tmp/email-previews/index.html
//
// Pure rendering — no DB, no Anthropic, no Resend. Safe to run anywhere.

import fs from 'node:fs'
import path from 'node:path'
import {
  renderDunningEmailHtml,
  renderWinbackEmailHtml,
  renderPersonalExitEmailHtml,
  renderPasswordResetHtml,
  renderVerificationEmailHtml,
  renderOnboardingNudgeHtml,
  renderDormantWarningHtml,
  renderPilotEndingHtml,
  renderFounderHandoffHtml,
} from '../src/winback/lib/email-html'

const OUT_DIR = '/tmp/email-previews'

interface Preview {
  filename: string
  label:    string
  html:     string
}

const previews: Preview[] = [
  // PR — the live exit-email render. Plain personal note (no card /
  // eyebrow / button), reply cue, demoted resubscribe link, unsubscribe
  // at the bottom. This is what scheduleExitEmail now sends (style:
  // 'personal'). Compare against the marketing renders below, which the
  // promo / re-engagement paths still use.
  {
    filename: '00-exit-personal.html',
    label:    'Exit email — PERSONAL render (live: maximises replies)',
    html: renderPersonalExitEmailHtml({
      body: `Hi Priya,

Fair point on the price — pricing fit is real and I'd rather know than guess. What price would have actually worked for your team?

— Thejas`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
    }),
  },
  // Win-back family — body uses the canonical LLM shape (greeting + 2
  // sentences + sign-off). Note: in production the body is generated by
  // the LLM; we hard-code one here just to show the wrapper.
  // NOTE: these now render the MARKETING shell (promo / re-engagement
  // path). The exit email itself uses the personal render above.
  {
    filename: '01-reengagement-reply-cue.html',
    label:    'Re-engagement ("I shipped your thing") — MARKETING render + reply cue',
    html: renderWinbackEmailHtml({
      body: `Hi Jordan,

I just shipped the Slack integration you wanted — messages post to any channel the moment a new order comes in. Worth another look?

— Thejas`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
      replyCue: true,
    }),
  },
  {
    filename: '01b-promo-button-only.html',
    label:    'Promo offer — MARKETING render, button only (no reply cue)',
    html: renderWinbackEmailHtml({
      body: `Hi Sam,

Saw price was the holdup — I've put 20% off your next 3 months on the table with code WINBACK20. Worth another look?

— Alex`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
    }),
  },
  {
    filename: '02-winback-tier2.html',
    label:    'Tier-2 exit email (Stripe enum only)',
    html: renderWinbackEmailHtml({
      body: `Hi Sam,

Stripe flagged 'too expensive' — I'd rather hear it in your own words. One line is enough.

— Jamie`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
    }),
  },
  {
    filename: '03-winback-tier3-silent.html',
    label:    'Tier-3 silent-churn (hardcoded template — the one you screenshotted)',
    html: renderWinbackEmailHtml({
      body: `Hi C3,

Saw you cancelled us recently. If you have a minute, I'd love to know what we got wrong. Even one line is enough.

— The team`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/b432c44c-8ad3-45ed-ab7d-b7be0cb008e5',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/b432c44c-8ad3-45ed-ab7d-b7be0cb008e5?t=tok',
    }),
  },
  {
    filename: '04-winback-improvement-match.html',
    label:    'Improvement-match win-back (LLM-generated after we shipped a fix)',
    html: renderWinbackEmailHtml({
      body: `Hi Jamie,

I shipped the Zapier-HubSpot integration you asked for — two-way sync, no code, live now. Worth another look?

— Alex`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
    }),
  },
  {
    filename: '05-winback-promotion.html',
    label:    'Promotion win-back (discount-bearing for price cancellations)',
    html: renderWinbackEmailHtml({
      body: `Hi Jamie,

Saw price was the sticking point — I've put 25% off the next 3 months on the table with code WINBACK25. Worth another look?

— Alex`,
      reactivationUrl: 'https://winbackflow.co/api/reactivate/example-uuid',
      unsubscribeUrl:  'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
    }),
  },

  // Dunning family — already shipped, included here for visual consistency check
  {
    filename: '06-dunning-t1-retry.html',
    label:    'Dunning T1 — retry pending (already styled, unchanged)',
    html: renderDunningEmailHtml({
      customerName: 'Sarah',
      planName:     'Pro',
      amount:       '49.00',
      currency:     'usd',
      retryDateStr: '2 May',
      updateLink:   'https://winbackflow.co/api/update-payment/example-uuid',
      unsubLink:    'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
      fromName:     'Acme',
      isFinalRetry: false,
    }),
  },
  {
    filename: '07-dunning-t3-final.html',
    label:    'Dunning T3 — last retry (already styled, unchanged)',
    html: renderDunningEmailHtml({
      customerName: 'Sarah',
      planName:     'Pro',
      amount:       '49.00',
      currency:     'usd',
      retryDateStr: '2 May',
      updateLink:   'https://winbackflow.co/api/update-payment/example-uuid',
      unsubLink:    'https://winbackflow.co/api/unsubscribe/example-uuid?t=tok',
      fromName:     'Acme',
      isFinalRetry: true,
    }),
  },

  // Founder-account transactional emails
  {
    filename: '08-password-reset.html',
    label:    'Password reset',
    html: renderPasswordResetHtml({
      resetUrl: 'https://winbackflow.co/auth/reset?token=example-token',
    }),
  },
  {
    filename: '09-email-verification.html',
    label:    'Email verification (signup confirmation)',
    html: renderVerificationEmailHtml({
      founderName: 'Alex',
      verifyUrl:   'https://winbackflow.co/auth/verify?token=example-token',
    }),
  },
  {
    filename: '10-onboarding-nudge.html',
    label:    'Day-3 onboarding nudge (signed up, did not connect Stripe)',
    html: renderOnboardingNudgeHtml({
      founderName: 'Alex',
      connectUrl:  'https://winbackflow.co/onboarding/stripe',
    }),
  },
  {
    filename: '11-dormant-warning.html',
    label:    'Day-83 dormant deletion warning',
    html: renderDormantWarningHtml({
      founderName: 'Alex',
      connectUrl:  'https://winbackflow.co/onboarding/stripe',
    }),
  },
  {
    filename: '12-pilot-ending.html',
    label:    'Pilot ending soon (informational, no CTA)',
    html: renderPilotEndingHtml({
      founderName: 'Alex',
      dateStr:     '5 June 2026',
    }),
  },

  // Founder-handoff — internal email, mailto CTA
  {
    filename: '13-founder-handoff.html',
    label:    'Founder handoff notification (internal — mailto CTA)',
    html: renderFounderHandoffHtml({
      body: `Hi Alex,

Sarah Connor is worth a personal reply — my reasoning is below.

──────────────────────────────────────
Recovery likelihood: HIGH
Why I'm handing off: They're explicitly asking to speak to someone and mentioned pricing flexibility twice — a short personal reply has a real shot.
──────────────────────────────────────

──────────────────────────────────────
SUBSCRIBER
Sarah Connor — sarah@example.com
Plan: Pro ($49.00/mo)
Cancelled: 3 days ago
Reason: Switched to a competitor
What they need: Roadmap clarity on Zapier-HubSpot two-way sync
──────────────────────────────────────

CONVERSATION HISTORY:

[Day 3] You sent: exit
  Subject: about the csv export
[Day 1] Sarah replied

LATEST REPLY TEXT:
"Honestly the CSV cap was the dealbreaker — happy to come back if it's gone."
──────────────────────────────────────`,
      mailtoUrl:    'mailto:sarah@example.com?subject=Re%3A%20About%20your%20subscription&body=...',
      mailtoLabel:  'Reply to Sarah',
      dashboardUrl: 'https://winbackflow.co/dashboard?subscriber=example-uuid',
    }),
  },
]

function buildIndex(): string {
  const rows = previews.map((p) =>
    `<li><a href="${p.filename}" style="font-family:-apple-system,sans-serif;color:#0f172a;text-decoration:none;font-size:14px;line-height:2;">${p.label}</a></li>`,
  ).join('\n  ')
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Email previews</title></head>
<body style="font-family:-apple-system,sans-serif;max-width:720px;margin:40px auto;padding:0 20px;color:#0f172a;">
  <h1 style="font-size:20px;margin:0 0 16px 0;">Email previews</h1>
  <p style="color:#475569;font-size:14px;">${previews.length} email types, rendered to disk. Open each file in a browser to preview.</p>
  <ol style="margin-top:20px;padding-left:0;list-style-position:inside;">
  ${rows}
  </ol>
</body></html>`
}

function main(): void {
  fs.mkdirSync(OUT_DIR, { recursive: true })
  for (const p of previews) {
    fs.writeFileSync(path.join(OUT_DIR, p.filename), p.html)
  }
  fs.writeFileSync(path.join(OUT_DIR, 'index.html'), buildIndex())
  console.log(`✓ Wrote ${previews.length} previews + index.html to ${OUT_DIR}`)
  console.log(`Open: file://${OUT_DIR}/index.html`)
}

main()
